line-length = 100
target-version = "py310"

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "COM",  # flake8-commas
  "UP",  # pyupgrade
]

[lint.per-file-ignores]
"tests/*" = ["S101"]
